name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: 0 0/8 * * *

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Maven Build
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t model-api:latest .